/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health Status
         * @description Return backend liveness information.
         *
         *     Args:
         *         None.
         *
         *     Returns:
         *         HealthResponse: Service status payload.
         */
        get: operations["get_health_status_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Backtest
         * @description Run a single backtest job with validated request payload.
         *
         *     Args:
         *         payload: User-requested backtest parameters.
         *         service: Service layer dependency handling backtest orchestration.
         *
         *     Returns:
         *         BacktestRunResponse: Structured summary for frontend display.
         */
        post: operations["run_backtest_api_v1_backtests_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Return a simple root payload.
         *
         *     Args:
         *         None.
         *
         *     Returns:
         *         dict[str, str]: Service identity payload.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestCapitalPoint
         * @description 投入金额与总资产对比曲线点。
         */
        BacktestCapitalPoint: {
            /**
             * Date
             * Format: date
             * @description 该数据点对应的交易日期
             */
            date: string;
            /**
             * Invested Capital
             * @description 截至该日期累计投入的本金，单位为人民币元
             */
            invested_capital: number;
            /**
             * Total Value
             * @description 截至该日期账户总资产，单位为人民币元
             */
            total_value: number;
        };
        /**
         * BacktestDailyRecord
         * @description 结果页明细表使用的日级记录。
         */
        BacktestDailyRecord: {
            /**
             * Date
             * Format: date
             * @description 该明细记录对应的交易日期
             */
            date: string;
            /**
             * Invested Capital
             * @description 截至该日期累计投入本金，单位为人民币元
             */
            invested_capital: number;
            /**
             * Cash Balance
             * @description 截至该日期账户剩余现金，单位为人民币元
             */
            cash_balance: number;
            /**
             * Position Value
             * @description 截至该日期持仓市值，单位为人民币元
             */
            position_value: number;
            /**
             * Total Value
             * @description 截至该日期账户总资产，单位为人民币元
             */
            total_value: number;
            /**
             * Units Held
             * @description 截至该日期持有的份额数量
             */
            units_held: number;
            /**
             * Nav
             * @description 标准化后的净值；回测起点通常归一为 1
             */
            nav: number;
            /**
             * Drawdown Pct
             * @description 该日期的回撤值，单位为百分比；通常为负值
             */
            drawdown_pct: number;
            /**
             * Event
             * @description 该日期的事件标记，例如 run_started、run_completed；无事件时为空
             */
            event?: string | null;
        };
        /**
         * BacktestRunRequest
         * @description 单次回测请求体。
         *
         *     说明：
         *         该结构描述用户从参数页提交到后端的一次完整回测配置。
         *         当前虽然 MVP 只落地 `dca`，但 `strategy_id` 属于已明确的核心扩展点，因此保留。
         */
        BacktestRunRequest: {
            /**
             * Symbol
             * @description ETF 代码，例如 510300；当前约定只接受 A 股 ETF 标的代码
             */
            symbol: string;
            /**
             * Start Date
             * Format: date
             * @description 回测开始日期，格式为 YYYY-MM-DD；该日期当天纳入回测区间
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description 回测结束日期，格式为 YYYY-MM-DD；该日期当天纳入回测区间
             */
            end_date: string;
            /**
             * Strategy Id
             * @description 策略标识；当前默认且唯一有效值是 dca，后续新增策略时仍沿用该入口字段
             * @default dca
             */
            strategy_id: string;
            /**
             * Initial Capital
             * @description 初始现金，单位为人民币元；表示回测开始时账户已有的可用现金
             * @default 0
             */
            initial_capital: number;
            /**
             * Periodic Investment Amount
             * @description 每次定投金额，单位为人民币元；按投资频率触发时投入该金额
             * @default 1000
             */
            periodic_investment_amount: number;
            /**
             * Investment Frequency
             * @description 定投频率；weekly 表示按周定投，monthly 表示按月定投
             * @default monthly
             * @enum {string}
             */
            investment_frequency: "weekly" | "monthly";
            /**
             * Monthly Investment Day
             * @description 按月定投时使用的每月执行日，仅在 investment_frequency=monthly 时有效，取值范围 1-28
             * @default 1
             */
            monthly_investment_day: number | null;
            /**
             * Weekly Investment Weekday
             * @description 按周定投时使用的执行日，仅在 investment_frequency=weekly 时有效；1 表示周一，5 表示周五
             */
            weekly_investment_weekday?: (1 | 2 | 3 | 4 | 5) | null;
            /** @description 本次回测使用的成本模型配置；用于控制佣金、滑点等交易成本口径 */
            cost_model?: components["schemas"]["CostModelConfig"];
        };
        /**
         * BacktestRunResponse
         * @description 单次回测成功响应体。
         *
         *     说明：
         *         该结构覆盖结果页指标、图表、明细和可追溯信息，
         *         前端应直接基于该结构渲染，不再自行重组另一套近似数据结构。
         */
        BacktestRunResponse: {
            /**
             * Run Id
             * @description 本次回测运行 ID；用于标识一次独立运行结果
             */
            run_id: string;
            /**
             * Request Id
             * @description 本次请求的追踪 ID；用于排查问题和关联日志
             */
            request_id: string;
            /**
             * Strategy Id
             * @description 本次运行实际执行的策略标识；当前通常为 dca
             */
            strategy_id: string;
            /**
             * Engine Version
             * @description 回测引擎版本；用于标记当前结果对应的引擎口径
             */
            engine_version: string;
            /**
             * Metric Definition Version
             * @description 指标定义版本；用于标记收益率、回撤、夏普等指标的计算口径版本
             */
            metric_definition_version: string;
            /** @description 本次运行的输入快照；用于可复现性、导出和结果追溯 */
            input_snapshot: components["schemas"]["BacktestRunRequest"];
            /** @description 结果摘要指标；供结果页指标卡直接展示 */
            summary: components["schemas"]["BacktestSummary"];
            /**
             * Nav Series
             * @description 净值曲线数据；供结果页净值图直接使用
             */
            nav_series: components["schemas"]["BacktestTimeSeriesPoint"][];
            /**
             * Drawdown Series
             * @description 回撤曲线数据；供结果页回撤图直接使用
             */
            drawdown_series: components["schemas"]["BacktestTimeSeriesPoint"][];
            /**
             * Capital Curve
             * @description 累计投入与总资产对比曲线；供结果页资金曲线图直接使用
             */
            capital_curve: components["schemas"]["BacktestCapitalPoint"][];
            /**
             * Records
             * @description 日级明细记录；供结果页明细表和后续导出能力直接使用
             */
            records: components["schemas"]["BacktestDailyRecord"][];
            /**
             * Message
             * @description 执行结果说明；用于告诉前端当前返回的是正式结果还是占位结果
             */
            message: string;
        };
        /**
         * BacktestSummary
         * @description 回测结果摘要指标。
         *
         *     说明：
         *         该结构用于结果页的指标卡区域，是前端展示核心指标的唯一来源。
         */
        BacktestSummary: {
            /**
             * Total Return Pct
             * @description 累计收益率，单位为百分比，例如 6.5 表示 6.5%
             */
            total_return_pct: number;
            /**
             * Annualized Return Pct
             * @description 年化收益率，单位为百分比
             */
            annualized_return_pct: number;
            /**
             * Max Drawdown Pct
             * @description 最大回撤，单位为百分比；通常为负值
             */
            max_drawdown_pct: number;
            /**
             * Annualized Volatility Pct
             * @description 年化波动率，单位为百分比
             */
            annualized_volatility_pct: number;
            /**
             * Sharpe Ratio
             * @description 夏普比率；当前按后端统一指标定义口径计算
             */
            sharpe_ratio: number;
            /**
             * Trading Days
             * @description 本次回测覆盖的交易日数量
             */
            trading_days: number;
        };
        /**
         * BacktestTimeSeriesPoint
         * @description 前端图表使用的通用时间序列点。
         */
        BacktestTimeSeriesPoint: {
            /**
             * Date
             * Format: date
             * @description 该数据点对应的交易日期
             */
            date: string;
            /**
             * Value
             * @description 该日期对应的数值；具体含义取决于所在序列
             */
            value: number;
        };
        /**
         * CostModelConfig
         * @description 回测成本模型配置。
         *
         *     说明：
         *         该结构表示一次回测运行时使用的成本参数。
         *         当前先保留最小成本模型字段，后续真实引擎接入时继续沿用这套口径。
         */
        CostModelConfig: {
            /**
             * Enabled
             * @description 是否启用交易成本；为 false 时，本次回测忽略佣金和滑点参数
             * @default true
             */
            enabled: boolean;
            /**
             * Commission Rate
             * @description 佣金费率，按成交金额乘以该比例计算；单位为比例值，例如 0.0003 表示万分之三
             * @default 0.0003
             */
            commission_rate: number;
            /**
             * Min Commission
             * @description 单笔交易最低佣金，单位为人民币元；当按费率计算结果低于该值时，取该最低值
             * @default 5
             */
            min_commission: number;
            /**
             * Slippage Rate
             * @description 滑点比例占位字段；当前默认值为 0，真实滑点逻辑接入后按该字段生效
             * @default 0
             */
            slippage_rate: number;
        };
        /**
         * ErrorResponse
         * @description 统一错误响应体。
         *
         *     说明：
         *         所有对前端可见的接口错误，最终都应收敛到这套结构，
         *         避免不同接口返回不同形状的错误对象。
         */
        ErrorResponse: {
            /**
             * Code
             * @description 稳定的机器可读错误码，例如 validation_error
             */
            code: string;
            /**
             * Message
             * @description 给人看的错误摘要，用于前端提示或日志展示
             */
            message: string;
            /**
             * Details
             * @description 结构化错误详情；可用于承载字段级校验信息、请求路径或额外调试信息
             */
            details?: unknown | null;
            /**
             * Request Id
             * @description 请求追踪 ID；用于关联日志、错误排查和用户反馈
             */
            request_id: string;
        };
        /**
         * HealthResponse
         * @description 健康检查响应体。
         */
        HealthResponse: {
            /**
             * Status
             * @description 服务健康状态；当前预期固定返回 ok
             */
            status: string;
            /**
             * Service
             * @description 服务标识；用于区分当前返回结果来自哪个后端服务
             */
            service: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_status_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_backtest_api_v1_backtests_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunResponse"];
                };
            };
            /** @description Request payload validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
